/**
 * GTC-145 — DEPRECATED.
 *
 * The per-section incremental generation pattern (GTC-121) was reverted on the
 * `experiment/single-ai-call` branch. The Moment 2 modal no longer fires this
 * endpoint when an accordion closes; the entire plan is generated in a single
 * call via `/api/events/[id]/finalize-plan`.
 *
 * This handler is intentionally left in place as a defensive 410 Gone so any
 * stale clients, scripts, or future callers hit a clear error rather than
 * accidentally re-introducing per-section generation.
 */

import { NextResponse } from 'next/server';

export async function POST() {
  return NextResponse.json(
    {
      error:
        'generate-section is deprecated (GTC-145). Plans are now generated by a single call to /api/events/[id]/finalize-plan.',
    },
    { status: 410 }
  );
}
