'use client';

import { useEffect, useState, useRef } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import {
  AlertCircle,
  Clock,
  Send,
  Eye,
  CheckCircle,
  Lock,
  Users,
  Home,
  Grid3x3,
  List,
  ChevronDown,
  ChevronRight,
  Maximize2,
  Minimize2,
} from 'lucide-react';
import TransitionModal from '@/components/plan/TransitionModal';
import { ModalProvider } from '@/contexts/ModalContext';
import { HostPersonModal } from '@/components/h/HostPersonModal';

interface Item {
  id: string;
  name: string;
  quantity: string | null;
  critical: boolean;
  status: string;
  glutenFree: boolean;
  dairyFree: boolean;
  vegetarian: boolean;
  notes: string | null;
  dropOffAt: string | null;
  dropOffLocation: string | null;
  dropOffNote: string | null;
  day: { id: string; name: string; date: string } | null;
  assignment: {
    id: string;
    response: 'PENDING' | 'ACCEPTED' | 'DECLINED';
    person: { id: string; name: string };
  } | null;
}

interface Team {
  id: string;
  name: string;
  scope: string | null;
  coordinator: {
    id: string;
    name: string;
  };
  status: string;
  itemCount: number;
  unassignedCount: number;
  criticalGapCount: number;
  items: Item[];
}

type PersonSummary = {
  id: string;
  name: string;
  status: 'NOT_SENT' | 'SENT' | 'OPENED' | 'RESPONDED';
  response: 'PENDING' | 'ACCEPTED' | 'DECLINED';
  rsvpStatus: string;
};

interface HostData {
  person: {
    id: string;
    name: string;
  };
  event: {
    id: string;
    name: string;
    startDate: string;
    endDate: string;
    status: string;
    guestCount: number | null;
  };
  authStatus: 'unclaimed' | 'requires_signin' | 'authenticated';
  teams: Team[];
  freezeAllowed: boolean;
  criticalGapCount: number;
  inviteStatus: {
    total: number;
    notSent: number;
    sent: number;
    opened: number;
    responded: number;
    inviteSendConfirmedAt: string | null;
  } | null;
  people: PersonSummary[] | null;
}

interface PlanData {
  eventName: string;
  eventDate: string;
  people: {
    name: string;
    items: string[];
    status: 'confirmed' | 'pending' | 'declined';
    phone?: string;
    email?: string;
  }[];
}

function formatPlanAsText(data: PlanData): string {
  const lines: string[] = [];

  lines.push(`${data.eventName}`);
  lines.push(`Date: ${data.eventDate}`);
  lines.push('');
  lines.push('─'.repeat(40));
  lines.push('');

  const confirmed = data.people.filter((p) => p.status === 'confirmed');
  if (confirmed.length > 0) {
    lines.push('✓ CONFIRMED:');
    confirmed.forEach((p) => {
      lines.push(`  ${p.name}: ${p.items.join(', ')}`);
    });
    lines.push('');
  }

  const pending = data.people.filter((p) => p.status === 'pending');
  if (pending.length > 0) {
    lines.push('⏳ WAITING FOR RESPONSE:');
    pending.forEach((p) => {
      const contact = p.phone || p.email || '';
      lines.push(`  ${p.name}: ${p.items.join(', ')}${contact ? ` — ${contact}` : ''}`);
    });
    lines.push('');
  }

  const declined = data.people.filter((p) => p.status === 'declined');
  if (declined.length > 0) {
    lines.push('❌ DECLINED (needs reassignment):');
    declined.forEach((p) => {
      lines.push(`  ${p.name}: ${p.items.join(', ')}`);
    });
    lines.push('');
  }

  lines.push('─'.repeat(40));
  lines.push(`Generated by Gather — ${new Date().toLocaleString()}`);

  return lines.join('\n');
}

function StatusIcon({ status }: { status: string }) {
  switch (status) {
    case 'NOT_SENT':
      return <Clock className="size-4 text-gray-400" />;
    case 'SENT':
      return <Send className="size-4 text-blue-500" />;
    case 'OPENED':
      return <Eye className="size-4 text-amber-500" />;
    case 'RESPONDED':
      return <CheckCircle className="size-4 text-green-500" />;
    default:
      return null;
  }
}

function ResponseBadge({ response }: { response: string }) {
  switch (response) {
    case 'ACCEPTED':
      return (
        <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-green-100 text-green-700">
          Confirmed
        </span>
      );
    case 'DECLINED':
      return (
        <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-red-100 text-red-700">
          Declined
        </span>
      );
    default:
      return (
        <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-gray-100 text-gray-500">
          Pending
        </span>
      );
  }
}

export default function HostView() {
  const params = useParams();
  const token = params.token as string;
  const [data, setData] = useState<HostData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [updating, setUpdating] = useState(false);
  const [editingGuestCount, setEditingGuestCount] = useState(false);
  const [guestCountValue, setGuestCountValue] = useState<string>('');
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [collapsedTeams, setCollapsedTeams] = useState<Set<string>>(new Set());
  const isInitialLoad = useRef(true);
  const expandAll = useRef(false);
  const [claimEmail, setClaimEmail] = useState('');
  const [claimSubmitted, setClaimSubmitted] = useState(false);
  const [claimSubmitting, setClaimSubmitting] = useState(false);
  const [showFreezeModal, setShowFreezeModal] = useState(false);
  const [selectedPerson, setSelectedPerson] = useState<PersonSummary | null>(null);
  const [confirmingSent, setConfirmingSent] = useState(false);
  const [showAllPeople, setShowAllPeople] = useState(false);
  const [copyState, setCopyState] = useState<'idle' | 'copying' | 'copied'>('idle');

  // Check URL params on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const searchParams = new URLSearchParams(window.location.search);
      expandAll.current = searchParams.get('expand') === 'all';
    }
  }, []);

  useEffect(() => {
    fetchData();

    // Auto-refresh every 5 seconds to pick up participant responses
    const intervalId = setInterval(() => {
      fetchData();
    }, 5000);

    // Cleanup interval on unmount
    return () => clearInterval(intervalId);
  }, [token]);

  const fetchData = async () => {
    try {
      const response = await fetch(`/api/h/${token}`);
      if (!response.ok) {
        throw new Error('Failed to load data');
      }
      const result = await response.json();
      setData(result);

      // Only initialize collapsed state on first load
      if (isInitialLoad.current) {
        if (expandAll.current) {
          // If expand=all query param is present, start with all teams expanded
          setCollapsedTeams(new Set());
        } else {
          // Default behavior: start with all teams collapsed
          const allTeamIds = new Set<string>(result.teams.map((team: Team) => team.id));
          setCollapsedTeams(allTeamIds);
        }
        isInitialLoad.current = false;
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  const handleStatusChange = async (newStatus: string) => {
    if (!data) return;

    // Use TransitionModal for freezing
    if (data.event.status === 'CONFIRMING' && newStatus === 'FROZEN') {
      setShowFreezeModal(true);
      return;
    }

    let unfreezeReason: string | null = null;

    // Confirmation for FROZEN → COMPLETE (final state)
    if (data.event.status === 'FROZEN' && newStatus === 'COMPLETE') {
      const confirmed = window.confirm(
        'Mark event as COMPLETE?\n\n' +
          'This is a final action and cannot be undone. ' +
          'Once complete, no further changes can be made to the event.\n\n' +
          'Are you sure you want to continue?'
      );
      if (!confirmed) {
        return;
      }
    }

    // Prompt for reason when unfreezing
    if (data.event.status === 'FROZEN' && newStatus === 'CONFIRMING') {
      unfreezeReason = window.prompt(
        'Unfreezing Event\n\n' +
          'Please provide a reason for unfreezing this event.\n' +
          'This will be logged in the audit trail.'
      );

      if (unfreezeReason === null) {
        return;
      }

      if (unfreezeReason.trim() === '') {
        alert('A reason is required to unfreeze the event.');
        return;
      }
    }

    setUpdating(true);
    try {
      const response = await fetch(`/api/h/${token}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          status: newStatus,
          unfreezeReason: unfreezeReason || undefined,
        }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to update status');
      }

      await fetchData();
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to update status');
    } finally {
      setUpdating(false);
    }
  };

  const handleEditGuestCount = () => {
    setGuestCountValue(data?.event.guestCount?.toString() || '');
    setEditingGuestCount(true);
  };

  const handleSaveGuestCount = async () => {
    if (!data) return;

    const newCount = guestCountValue.trim() === '' ? null : parseInt(guestCountValue, 10);

    if (guestCountValue.trim() !== '' && (isNaN(newCount!) || newCount! < 0)) {
      alert('Please enter a valid number');
      return;
    }

    setUpdating(true);
    try {
      const response = await fetch(`/api/h/${token}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ guestCount: newCount }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to update guest count');
      }

      setEditingGuestCount(false);
      await fetchData();
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to update guest count');
    } finally {
      setUpdating(false);
    }
  };

  const handleCancelEditGuestCount = () => {
    setEditingGuestCount(false);
    setGuestCountValue('');
  };

  const toggleTeamCollapse = (teamId: string) => {
    const newCollapsed = new Set(collapsedTeams);
    if (newCollapsed.has(teamId)) {
      newCollapsed.delete(teamId);
    } else {
      newCollapsed.add(teamId);
    }
    setCollapsedTeams(newCollapsed);
  };

  const toggleAllTeams = () => {
    if (collapsedTeams.size === 0) {
      // All expanded, collapse all
      const allIds = new Set(data?.teams.map((team) => team.id) || []);
      setCollapsedTeams(allIds);
    } else {
      // Some or all collapsed, expand all
      setCollapsedTeams(new Set());
    }
  };

  const handleClaimSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!data || !claimEmail.trim()) return;

    setClaimSubmitting(true);
    try {
      const response = await fetch('/api/auth/claim', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: claimEmail.trim(),
          personId: data.person.id,
          returnToken: token,
        }),
      });

      const result = await response.json();
      if (result.ok) {
        setClaimSubmitted(true);
      }
    } catch (err) {
      console.error('Claim submission error:', err);
      // Still show success to prevent enumeration
      setClaimSubmitted(true);
    } finally {
      setClaimSubmitting(false);
    }
  };

  const handleConfirmSent = async () => {
    setConfirmingSent(true);
    try {
      await fetch(`/api/h/${token}/confirm-invites-sent`, { method: 'POST' });
      await fetchData();
    } finally {
      setConfirmingSent(false);
    }
  };

  const handleCopyPlan = async () => {
    setCopyState('copying');
    try {
      const res = await fetch(`/api/h/${token}/export-text`);
      if (!res.ok) throw new Error('Failed to export');
      const planData: PlanData = await res.json();
      const text = formatPlanAsText(planData);
      await navigator.clipboard.writeText(text);
      setCopyState('copied');
      setTimeout(() => setCopyState('idle'), 2000);
    } catch {
      setCopyState('idle');
    }
  };

  const formatDateRange = (startDate: string, endDate: string) => {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const formatter = new Intl.DateTimeFormat('en-NZ', {
      month: 'short',
      day: 'numeric',
      timeZone: 'Pacific/Auckland',
    });
    return `${formatter.format(start)}-${formatter.format(end).split(' ')[1]}`;
  };

  const getNextStatus = (currentStatus: string): string | null => {
    switch (currentStatus) {
      case 'DRAFT':
        return 'CONFIRMING';
      case 'CONFIRMING':
        return 'FROZEN';
      case 'FROZEN':
        return 'COMPLETE';
      default:
        return null;
    }
  };

  const canUnfreeze = (currentStatus: string): boolean => {
    return currentStatus === 'FROZEN';
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-gray-600">Loading...</div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-red-600">Error: {error || 'Failed to load'}</div>
      </div>
    );
  }

  // Show claim form if host account is unclaimed (Ticket 1.6)
  if (data.authStatus === 'unclaimed') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-6">
        <div className="max-w-md w-full bg-white rounded-lg shadow-lg p-8">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Claim Your Account</h1>
          <p className="text-gray-600 mb-6">
            To continue managing your events, enter your email to create an account.
          </p>

          {claimSubmitted ? (
            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <p className="text-green-800 font-semibold mb-2">Check your email!</p>
              <p className="text-green-700 text-sm">
                We've sent a magic link to <strong>{claimEmail}</strong>. Click the link in the
                email to complete your account setup and return to managing your events.
              </p>
            </div>
          ) : (
            <form onSubmit={handleClaimSubmit}>
              <label className="block text-sm font-medium text-gray-700 mb-2">Email Address</label>
              <input
                type="email"
                value={claimEmail}
                onChange={(e) => setClaimEmail(e.target.value)}
                placeholder="your@email.com"
                required
                disabled={claimSubmitting}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed mb-4"
              />
              <button
                type="submit"
                disabled={claimSubmitting || !claimEmail.trim()}
                className="w-full bg-accent text-white py-2 px-4 rounded-lg hover:bg-accent-dark disabled:bg-gray-300 disabled:cursor-not-allowed font-semibold"
              >
                {claimSubmitting ? 'Sending...' : 'Send Magic Link'}
              </button>
            </form>
          )}
        </div>
      </div>
    );
  }

  // Show sign-in prompt if account is claimed but user is not signed in (Ticket 1.6)
  if (data.authStatus === 'requires_signin') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-6">
        <div className="max-w-md w-full bg-white rounded-lg shadow-lg p-8">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Sign In Required</h1>
          <p className="text-gray-600 mb-6">
            This account has been claimed. Please sign in to continue managing your events.
          </p>
          <a
            href="/auth/signin"
            className="block w-full bg-accent text-white py-2 px-4 rounded-lg hover:bg-accent-dark text-center font-semibold"
          >
            Sign In
          </a>
        </div>
      </div>
    );
  }

  const nextStatus = getNextStatus(data.event.status);
  const totalGaps = data.teams.reduce((sum, t) => sum + t.unassignedCount, 0);

  // Sort teams alphabetically by name for stable ordering
  // Status badges (red/amber/green) provide visual priority without rearranging cards
  const sortedTeams = [...data.teams].sort((a, b) => a.name.localeCompare(b.name));

  const invitePct =
    data.inviteStatus && data.inviteStatus.total > 0
      ? Math.round((data.inviteStatus.responded / data.inviteStatus.total) * 100)
      : 0;

  return (
    <ModalProvider>
      <div className="min-h-screen flex flex-col bg-gray-50">
        {/* Header */}
        <div className="bg-white border-b border-gray-200 px-6 py-5">
          <Link
            href="/demo"
            className="inline-flex items-center gap-1 text-sm text-accent hover:text-sage-800 mb-3"
          >
            <Home className="size-4" />
            Back to Demo
          </Link>
          <div className="flex items-start justify-between mb-2">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{data.event.name}</h1>
              <p className="text-sm text-gray-600 mt-1">Host: {data.person.name}</p>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <button
                onClick={handleCopyPlan}
                disabled={copyState === 'copying'}
                className="px-3 py-1 bg-gray-100 text-gray-700 text-sm rounded hover:bg-gray-200 transition disabled:opacity-50"
              >
                {copyState === 'copied' ? '✓ Copied!' : copyState === 'copying' ? '...' : '📋 Copy Plan'}
              </button>
              <a
                href={`/h/${token}/audit`}
                className="px-3 py-1 bg-gray-600 text-white text-sm rounded hover:bg-gray-700 transition"
              >
                📋 Audit Log
              </a>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-500">
              {formatDateRange(data.event.startDate, data.event.endDate)}
            </span>
            <span className="text-gray-300">·</span>
            {editingGuestCount ? (
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  value={guestCountValue}
                  onChange={(e) => setGuestCountValue(e.target.value)}
                  className="px-2 py-1 border border-gray-300 rounded w-20 text-sm"
                  placeholder="Guests"
                  min="0"
                  disabled={updating}
                />
                <button
                  onClick={handleSaveGuestCount}
                  disabled={updating}
                  className="px-2 py-1 bg-sage-600 text-white text-xs rounded hover:bg-sage-700 disabled:bg-gray-300"
                >
                  Save
                </button>
                <button
                  onClick={handleCancelEditGuestCount}
                  disabled={updating}
                  className="px-2 py-1 bg-gray-400 text-white text-xs rounded hover:bg-gray-500 disabled:bg-gray-300"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <button
                onClick={handleEditGuestCount}
                className="text-sm text-accent hover:underline"
              >
                {data.event.guestCount ? `${data.event.guestCount} guests` : 'Add guest count'}
              </button>
            )}
          </div>
          <div className="flex items-center gap-2 mt-3">
            <span className="text-xs uppercase tracking-wide text-gray-500 bg-gray-100 px-2 py-1 rounded">
              {data.event.status}
            </span>
            {canUnfreeze(data.event.status) && (
              <button
                onClick={() => handleStatusChange('CONFIRMING')}
                disabled={updating}
                className="text-xs px-2 py-1 bg-yellow-600 text-white rounded hover:bg-yellow-700 disabled:bg-gray-300"
              >
                Unfreeze
              </button>
            )}
          </div>
        </div>

        {/* Status Banner - Only show in CONFIRMING status */}
        {data.event.status === 'CONFIRMING' && (
          <>
            {data.criticalGapCount > 0 ? (
              <div className="bg-red-50 px-6 py-4 flex items-center gap-3">
                <AlertCircle className="size-6 text-red-500" />
                <span className="font-semibold text-red-900">
                  {data.criticalGapCount} critical{' '}
                  {data.criticalGapCount === 1 ? 'gap remains' : 'gaps remain'}
                </span>
              </div>
            ) : totalGaps > 0 ? (
              <div className="bg-amber-50 px-6 py-4 flex items-center gap-3">
                <div className="size-6 rounded-full bg-amber-500 flex items-center justify-center text-white text-sm">
                  !
                </div>
                <span className="font-semibold text-amber-900">
                  Ready to freeze ({totalGaps} non-critical {totalGaps === 1 ? 'gap' : 'gaps'})
                </span>
              </div>
            ) : (
              <div className="bg-green-50 px-6 py-4 flex items-center gap-3">
                <div className="size-6 rounded-full bg-green-500 flex items-center justify-center text-white text-sm">
                  ✓
                </div>
                <span className="font-semibold text-green-900">Ready to freeze</span>
              </div>
            )}
          </>
        )}

        {/* Invite Status Summary - CONFIRMING only */}
        {data.event.status === 'CONFIRMING' && data.inviteStatus && (
          <div className="bg-white border-b px-6 py-4 space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
                Responses
              </h2>
              <span className="text-2xl font-bold text-gray-900">
                {data.inviteStatus.responded}/{data.inviteStatus.total}
                <span className="text-sm font-normal text-gray-500 ml-1">({invitePct}%)</span>
              </span>
            </div>

            {/* Multi-segment progress bar */}
            {data.inviteStatus.total > 0 && (
              <div className="flex h-2 rounded-full overflow-hidden bg-gray-100">
                <div
                  className="bg-green-500"
                  style={{
                    width: `${(data.inviteStatus.responded / data.inviteStatus.total) * 100}%`,
                  }}
                />
                <div
                  className="bg-amber-400"
                  style={{
                    width: `${(data.inviteStatus.opened / data.inviteStatus.total) * 100}%`,
                  }}
                />
                <div
                  className="bg-blue-400"
                  style={{
                    width: `${(data.inviteStatus.sent / data.inviteStatus.total) * 100}%`,
                  }}
                />
              </div>
            )}

            {/* Count row */}
            <div className="flex items-center gap-3 text-xs text-gray-500">
              {data.inviteStatus.notSent > 0 && (
                <span>{data.inviteStatus.notSent} not sent</span>
              )}
              {data.inviteStatus.sent > 0 && <span>{data.inviteStatus.sent} sent</span>}
              {data.inviteStatus.opened > 0 && <span>{data.inviteStatus.opened} opened</span>}
              {data.inviteStatus.responded > 0 && (
                <span className="text-green-600 font-medium">
                  {data.inviteStatus.responded} responded
                </span>
              )}
            </div>

            {/* Confirm sent button */}
            {!data.inviteStatus.inviteSendConfirmedAt && (
              <button
                onClick={handleConfirmSent}
                disabled={confirmingSent}
                className="w-full py-2 text-sm font-medium text-blue-700 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 disabled:opacity-50 transition-colors"
              >
                {confirmingSent ? 'Confirming...' : "I've sent the invites"}
              </button>
            )}
            {data.inviteStatus.inviteSendConfirmedAt && (
              <p className="text-xs text-gray-400">
                ✓ Invites confirmed sent{' '}
                {new Date(data.inviteStatus.inviteSendConfirmedAt).toLocaleDateString('en-NZ')}
              </p>
            )}
          </div>
        )}

        {/* People List - CONFIRMING only */}
        {data.event.status === 'CONFIRMING' && data.people && data.people.length > 0 && (
          <div className="bg-white border-b px-6 py-4">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500 mb-3">
              People
            </h2>
            <div className="space-y-1">
              {(showAllPeople ? data.people : data.people.slice(0, 6)).map((person) => (
                <button
                  key={person.id}
                  onClick={() => setSelectedPerson(person)}
                  className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg hover:bg-gray-50 transition-colors text-left"
                >
                  <StatusIcon status={person.status} />
                  <span className="flex-1 text-sm text-gray-800">{person.name}</span>
                  <ResponseBadge response={person.response} />
                </button>
              ))}
            </div>
            {data.people.length > 6 && (
              <div className="mt-3 text-center">
                <button
                  onClick={() => setShowAllPeople(!showAllPeople)}
                  className="text-sm text-gray-500 hover:text-gray-700"
                >
                  {showAllPeople ? 'Show less' : `Show all ${data.people.length}`}
                </button>
              </div>
            )}
          </div>
        )}

        {/* Teams List */}
        <div className="flex-1 overflow-y-auto p-4 md:p-6">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm uppercase tracking-wide text-gray-500">Teams</h2>
            <div className="flex items-center gap-2">
              {data && data.teams.length > 0 && (
                <button
                  onClick={toggleAllTeams}
                  className="flex items-center gap-2 px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors"
                >
                  {collapsedTeams.size === 0 ? (
                    <>
                      <Minimize2 className="size-4" />
                      Collapse All
                    </>
                  ) : (
                    <>
                      <Maximize2 className="size-4" />
                      Expand All
                    </>
                  )}
                </button>
              )}
              <div className="flex items-center gap-1 bg-gray-100 rounded-lg p-1">
                <button
                  onClick={() => setViewMode('grid')}
                  className={`p-1.5 rounded transition-colors ${
                    viewMode === 'grid'
                      ? 'bg-white text-gray-900 shadow-sm'
                      : 'text-gray-500 hover:text-gray-700'
                  }`}
                  title="Grid view"
                >
                  <Grid3x3 className="size-4" />
                </button>
                <button
                  onClick={() => setViewMode('list')}
                  className={`p-1.5 rounded transition-colors ${
                    viewMode === 'list'
                      ? 'bg-white text-gray-900 shadow-sm'
                      : 'text-gray-500 hover:text-gray-700'
                  }`}
                  title="List view"
                >
                  <List className="size-4" />
                </button>
              </div>
            </div>
          </div>
          <div
            className={`${viewMode === 'grid' ? 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 items-start' : 'flex flex-col gap-4 items-start'}`}
          >
            {sortedTeams.map((team) => {
              const assignedCount = team.items.filter((i) => i.assignment).length;
              const pendingCount = team.items.filter(
                (i) => i.assignment?.response === 'PENDING'
              ).length;
              const acceptedCount = team.items.filter(
                (i) => i.assignment?.response === 'ACCEPTED'
              ).length;
              const declinedCount = team.items.filter(
                (i) => i.assignment?.response === 'DECLINED'
              ).length;
              // Gap count includes unassigned items AND declined items
              const gapCount = team.items.filter(
                (i) => i.assignment === null || i.assignment?.response === 'DECLINED'
              ).length;
              const criticalGapCount = team.items.filter(
                (i) =>
                  i.critical && (i.assignment === null || i.assignment?.response === 'DECLINED')
              ).length;

              return (
                <div
                  key={team.id}
                  className={`bg-white rounded-lg border-2 shadow-sm hover:shadow-md transition-shadow p-5 ${
                    viewMode === 'list' ? 'w-full max-w-md' : ''
                  } ${
                    team.status === 'CRITICAL_GAP'
                      ? 'border-red-300'
                      : team.status === 'GAP'
                        ? 'border-amber-300'
                        : 'border-green-300'
                  }`}
                >
                  {/* Card Header - Always Visible */}
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-start gap-3 flex-1 min-w-0">
                      <div
                        className={`size-3 rounded-full mt-1.5 flex-shrink-0 ${
                          team.status === 'CRITICAL_GAP'
                            ? 'bg-red-500'
                            : team.status === 'GAP'
                              ? 'bg-amber-500'
                              : 'bg-green-500'
                        }`}
                      />
                      <div className="flex-1 min-w-0">
                        <h3 className="font-bold text-gray-900 text-lg mb-1">{team.name}</h3>
                        <p className="text-sm text-gray-600">{team.coordinator.name}</p>
                      </div>
                    </div>

                    {/* Collapse Toggle Button */}
                    <button
                      onClick={() => toggleTeamCollapse(team.id)}
                      className="ml-2 p-2 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors flex-shrink-0 border border-gray-300"
                      title={collapsedTeams.has(team.id) ? 'Expand' : 'Collapse'}
                    >
                      {collapsedTeams.has(team.id) ? (
                        <ChevronRight className="size-5 text-gray-700" />
                      ) : (
                        <ChevronDown className="size-5 text-gray-700" />
                      )}
                    </button>
                  </div>

                  {/* Status Badge - Always Visible */}
                  <div className="mb-3">
                    {team.status === 'CRITICAL_GAP' ? (
                      <div className="inline-flex items-center gap-1.5 bg-red-100 text-red-800 px-3 py-1.5 rounded-full text-sm font-semibold">
                        <AlertCircle className="size-4" />
                        {criticalGapCount} critical {criticalGapCount === 1 ? 'gap' : 'gaps'}
                      </div>
                    ) : team.status === 'GAP' ? (
                      <div className="inline-flex items-center gap-1.5 bg-amber-100 text-amber-800 px-3 py-1.5 rounded-full text-sm font-semibold">
                        <AlertCircle className="size-4" />
                        {gapCount} {gapCount === 1 ? 'gap' : 'gaps'}
                      </div>
                    ) : (
                      <div className="inline-flex items-center gap-1.5 bg-green-100 text-green-800 px-3 py-1.5 rounded-full text-sm font-semibold">
                        <Users className="size-4" />
                        All assigned
                      </div>
                    )}
                  </div>

                  {/* Collapsible Content */}
                  {!collapsedTeams.has(team.id) && (
                    <>
                      {/* Stats Grid */}
                      <div className="grid grid-cols-2 gap-3 pt-3 border-t border-gray-200">
                        <div>
                          <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                            Total Items
                          </div>
                          <div className="text-xl font-bold text-gray-900">{team.itemCount}</div>
                        </div>
                        <div>
                          <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                            Assigned
                          </div>
                          <div className="text-xl font-bold text-green-600">{assignedCount}</div>
                        </div>
                        <div>
                          <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                            Unassigned
                          </div>
                          <div
                            className={`text-xl font-bold ${team.unassignedCount > 0 ? 'text-amber-600' : 'text-gray-400'}`}
                          >
                            {team.unassignedCount}
                          </div>
                        </div>
                        <div>
                          <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                            Pending
                          </div>
                          <div className="text-xl font-bold text-gray-600">{pendingCount}</div>
                        </div>
                        <div>
                          <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                            Confirmed
                          </div>
                          <div className="text-xl font-bold text-green-600">{acceptedCount}</div>
                        </div>
                        <div>
                          <div className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                            Declined
                          </div>
                          <div className="text-xl font-bold text-red-600">{declinedCount}</div>
                        </div>
                      </div>

                      {/* View Items Button */}
                      <Link
                        href={`/h/${token}/team/${team.id}`}
                        className="mt-4 mx-auto w-1/3 flex items-center justify-center gap-1.5 px-3 py-1.5 bg-accent text-white text-sm rounded-lg hover:bg-accent-dark transition-colors"
                      >
                        <Eye className="size-3" />
                        View Items
                      </Link>
                    </>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Bottom Action Bar */}
        {data.event.status !== 'COMPLETE' && nextStatus && (
          <div className="bg-white border-t border-gray-200 px-6 py-4">
            <button
              onClick={() => handleStatusChange(nextStatus)}
              disabled={updating || (nextStatus === 'FROZEN' && !data.freezeAllowed)}
              className={`w-full h-14 rounded-lg font-semibold transition-all ${
                updating || (nextStatus === 'FROZEN' && !data.freezeAllowed)
                  ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                  : 'bg-accent text-white hover:bg-accent-dark'
              }`}
            >
              {updating ? (
                'Updating...'
              ) : nextStatus === 'FROZEN' ? (
                <span className="flex items-center justify-center gap-2">
                  <Lock className="size-5" />
                  Freeze Event
                </span>
              ) : (
                `${nextStatus === 'COMPLETE' ? 'Mark as ' : ''}${nextStatus}`
              )}
            </button>
            {nextStatus === 'FROZEN' && !data.freezeAllowed && (
              <p className="text-center text-sm text-red-600 mt-2">
                Cannot freeze: {data.criticalGapCount} critical{' '}
                {data.criticalGapCount === 1 ? 'gap' : 'gaps'}
              </p>
            )}
          </div>
        )}

        {/* Freeze Modal */}
        {showFreezeModal && data && (
          <TransitionModal
            eventId={data.event.id}
            currentStatus="CONFIRMING"
            onClose={() => setShowFreezeModal(false)}
            onSuccess={() => {
              setShowFreezeModal(false);
              fetchData();
            }}
          />
        )}

        {/* Person Detail Modal */}
        {selectedPerson && (
          <HostPersonModal
            token={token}
            person={selectedPerson}
            onClose={() => setSelectedPerson(null)}
            onUpdate={() => {
              setSelectedPerson(null);
              fetchData();
            }}
          />
        )}
      </div>
    </ModalProvider>
  );
}
